--- # config file for validator 1
id: 1
heightvoteset:
  3: 
    round: 3
    received_prevote:
      - type: PREVOTE
        sender: 2
        round: 3
        value: 10

      - type: PREVOTE
        sender: 3
        round: 3
        value: 10

      - type: PREVOTE
        sender: 4
        round: 3
        value: 10

    received_precommit:
      - type: PRECOMMIT
        sender: 1
        round: 3
        value: 10

      - type: PRECOMMIT
        sender: 2
        round: 3
        value: 10

      - type: PRECOMMIT
        sender: 3
        round: 3
        value: 10

    sent_prevote:
      - type: PREVOTE
        sender: 1
        round: 3
        value: 20

    sent_precommit:
      - type: PRECOMMIT
        sender: 1
        round: 3
        value: 10
