%YAML validators config
---

p1: 1
heightvoteset:
  3:
    - voteset
      round: 3

      received_prevote:
        - message
          sender: 2
          round: 3
          value: 10

        - message
          sender: 3
          round: 3
          value: 10

        - message
          sender: 4
          round: 3
          value: 10

      received_precommit:
        - message
          sender: 1
          round: 3
          value: 10

        - message
          sender: 2
          round: 3
          value: 10

        - message
          sender: 3
          round: 3
          value: 10

      sent_prevote:
        - message
          sender: 1
          round: 3
          value: 20

      sent_precommit:
        - message
          sender: 1
          round: 3
          value: 10


p2:
  - voteset
    round: 3

    received_prevote:
      - message
        sender: 2
        value: 10

      - message
        sender: 3
        value: 10

      - message
        sender: 4
        value: 10

      - message
        sender: 1
        value: 20

      - message
        sender: 3
        value: 20

      - message
        sender: 4
        value: 20

    received_precommit:

    sent_prevote:
      - message
        sender: 2
        value: 10

    sent_precommit:
      - message
        sender: 2
        value: 10

  - voteset
    round: 4

    received_prevote:
      - message
        sender: 2
        value: 20

      - message
        sender: 3
        value: 20

      - message
        sender: 4
        value: 20

    received_precommit:
      - message
        sender: 2
        value: 20

      - message
        sender: 3
        value: 20

      - message
        sender: 4
        value: 20

    sent_prevote:
      - message
        sender: 2
        value: 20

    sent_precommit:
      - message
        sender: 2
        value: 20

p3:
  - voteset
    round: 3

    received_prevote:
      - message
        sender: 2
        value: 10

      - message
        sender: 3
        value: 10

      - message
        sender: 4
        value: 10

    received_precommit:
     

    sent_prevote:
      - message
        sender: 3
        value: 10

    sent_precommit:
      - message
        sender: 3
        value: 10

  - voteset
    round: 4

    received_prevote:
      - message
        sender: 2
        value: 20

      - message
        sender: 3
        value: 20

      - message
        sender: 4
        value: 20

    received_precommit:
     

    sent_prevote:
      - message
        sender: 3
        value: 20

    sent_precommit:
      - message
        sender: 3
        value: 20

p4:
  - voteset
    round: 3

    received_prevote:
      - message
        sender: 2
        value: 10

      - message
        sender: 3
        value: 10

      - message
        sender: 4
        value: 10

    received_precommit:
     

    sent_prevote:
      - message
        sender: 3
        value: 10

    sent_precommit:
      - message
        sender: 3
        value: 10

  - voteset
    round: 4

    received_prevote:
      - message
        sender: 2
        value: 20

      - message
        sender: 3
        value: 20

      - message
        sender: 4
        value: 20

    received_precommit:
     

    sent_prevote:
      - message
        sender: 4
        value: 20

    sent_precommit:
      - message
        sender: 4
        value: 20

...