name: Build and Tests

on: [push, pull_request]
jobs:

  run:
    name: run
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -covermode=count -coverprofile=coverage.out

      - name: Codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          # User defined upload name. Visible in Codecov UI
          # name: # optional
          # Repository upload token - get it from codecov.io. Required only for private repositories
          # token: # optional

          # Path to coverage file to upload
          file: ./coverage.out

          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          # flags: # optional

          # Specify whether or not CI build should fail if Codecov runs into an error during upload
          fail_ci_if_error: true

      - name: Publish monitor docker image
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          # The name of the image you would like to push
          name: mikanikos/fork-accountability/monitor
          # The login username for the registry
          username: ${{ github.actor }}
          # The login password for the registry
          password: ${{ secrets.GITHUB_TOKEN }}
          # Use registry for pushing to a custom registry
          registry: docker.pkg.github.com
          dockerfile: cmd/monitor/Dockerfile  
      
      - name: Publish validator docker image
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          # The name of the image you would like to push
          name: mikanikos/fork-accountability/validator
          # The login username for the registry
          username: ${{ github.actor }}
          # The login password for the registry
          password: ${{ secrets.GITHUB_TOKEN }}
          # Use registry for pushing to a custom registry
          registry: docker.pkg.github.com
          # Use dockerfile to specifiy the Dockerfile to build
          dockerfile: cmd/validator/Dockerfile
          
      - name: Fetch releases
        run: |
          curl -X POST \
            -s \
            -H "Accept: application/vnd.github.package-deletes-preview+json" \
            -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"query":"query {repository(owner:\"${{ OWNER }}\", name:\"${{ REPOSITORY }}\") {registryPackages(last:1) {edges{node{id, name, versions(last:100){edges {node {id, updatedAt, version}}}}}}}}"}' \
            -o /tmp/response.json \
            --url https://api.github.com/graphql
