name: Build and Test

on: [push, pull_request]
jobs:

  run:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./... -covermode=count -coverprofile=coverage.out
    
    - name: Upload report to Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        # User defined upload name. Visible in Codecov UI
        # name: # optional
        # Repository upload token - get it from codecov.io. Required only for private repositories
        # token: # optional
        
        # Path to coverage file to upload
        file: ./coverage.out
        
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        # flags: # optional
        
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
